/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpinner: typeof import('element-plus/es')['ElSpinner']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LoginForm: typeof import('./src/components/common/LoginForm.vue')['default']
    NavBar: typeof import('./src/components/common/NavBar.vue')['default']
    ProblemDetail: typeof import('./src/components/problem/ProblemDetail.vue')['default']
    ProblemList: typeof import('./src/components/problem/ProblemList.vue')['default']
    ProblemUpload: typeof import('./src/components/problem/ProblemUpload.vue')['default']
    RegisterForm: typeof import('./src/components/common/RegisterForm.vue')['default']
    SubmissionDetail: typeof import('./src/components/submission/SubmissionDetail.vue')['default']
    SubmissionList: typeof import('./src/components/submission/SubmissionList.vue')['default']
    UserList: typeof import('./src/components/user/UserList.vue')['default']
    UserProfile: typeof import('./src/components/user/UserProfile.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
  const ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSpinner: typeof import('element-plus/es')['ElSpinner']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
  const LoginForm: typeof import('./src/components/common/LoginForm.vue')['default']
  const NavBar: typeof import('./src/components/common/NavBar.vue')['default']
  const ProblemDetail: typeof import('./src/components/problem/ProblemDetail.vue')['default']
  const ProblemList: typeof import('./src/components/problem/ProblemList.vue')['default']
  const ProblemUpload: typeof import('./src/components/problem/ProblemUpload.vue')['default']
  const RegisterForm: typeof import('./src/components/common/RegisterForm.vue')['default']
  const SubmissionDetail: typeof import('./src/components/submission/SubmissionDetail.vue')['default']
  const SubmissionList: typeof import('./src/components/submission/SubmissionList.vue')['default']
  const UserList: typeof import('./src/components/user/UserList.vue')['default']
  const UserProfile: typeof import('./src/components/user/UserProfile.vue')['default']
}